name: ruam_mit_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  path: ^1.9.1
  sqflite: ^2.4.2
  typewritertext: ^3.0.9
  mysql_client: ^0.0.27
  http: ^1.2.0
  flutter_dotenv: ^5.2.1
  image_picker: ^1.0.4
  path_provider: ^2.1.2
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Prompt
      fonts:
        - asset: fonts/Prompt.ttf

  assets:
    - assets/
    - assets/app_logo.png
    - assets/app_logo_white.png
    - assets/police_banner.png
    - assets/login_button.png
    - assets/profile_banner.png
    - .env
    # - assets/icons/
    # - assets/icons/app_logo.svg